import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from './global.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Musicart',
    description: 'Generated by create next app'
};

const RootLayout = ({ children }: {children: React.ReactNode}) => {
    return (
        <html lang="en">
            <body className={styles.layout_homepage_wrapper}>{children}</body>
        </html>
    );
};

export default RootLayout;
